version: 2.1

jobs:
  helm:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: 
          name: "Install Helm"
          command: "curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash"
      - run:
          name: "Helm lint"
          command: "helm lint helm-charts/*"
      - run:
          name: "Helm Package"
          command: "helm package helm-charts/*"
      - run:
          name: "Helm repo index"
          command: "helm repo index --url http://schoenwald.me/helm-charts/ ."
         

workflows:
  helm-workflow:
    jobs:
      - helm